baseURL = "/"
languageCode = "en-us"
title = "The Magic Space of the IT"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Alexander Schneider"
    description = "Find what you seek or get lost"
    githubUsername = "kTitan"
    accent = "darkgray"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["bash", "mysql", "test", "php"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/historical-blog-posts/"
    name = "Historical Blog"
    weight = 2

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

#[[menu.icon]]
#    url = "mailto:mail@me.com"
#    name = "envelope-o"
#    weight = 1

[[menu.icon]]
    url = "https://github.com/kTitan/"
    name = "github"
    weight = 2
